### ISSUE TITLE
Question about attention ratio in Figure 4 and Figure 5

### ISSUE THREAD

**Issue by 421zuoduan** [lzhxmu/VTW#1]
Hi, thanks for your excellent work.

I have a question regarding the vertical axis of the line graphs in Figure 4 and Figure 5, which is labeled as `attention ratio`. Could you please provide more details on what the `attention ratio` represents in the context of your paper? . Additionally, I would appreciate it if you could explain how this value is calculated, which is presented as `we aggregate the attention scores of each input type`

**Comment by lzhxmu** [comment]
Hi, I'm glad that you pay attention to our work. 
To make it easier to understand, let's use vision tokens as an example. 
The attention ratio of vision tokens (\beta^{vis}) represents the total attention score of all vision tokens divide the  total attention of all tokens which is constantly equal to 1, and the 'aggregate' operation refers to summation.
Please refer to Sec3.2 for  more details about the attention ratio.

**Comment by lzhxmu** [comment]
> Hi, thanks for your excellent work.
> 
> I have a question regarding the vertical axis of the line graphs in Figure 4 and Figure 5, which is labeled as `attention ratio`. Could you please provide more details on what the `attention ratio` represents in the context of your paper? . Additionally, I would appreciate it if you could explain how this value is calculated, which is presented as `we aggregate the attention scores of each input type`

Hi, I'm glad that you pay attention to our work.
To make it easier to understand, let's use vision tokens as an example.
The attention ratio of vision tokens (\beta^{vis}) represents the total attention score of all vision tokens divide the total attention of all tokens which is constantly equal to 1, and the 'aggregate' operation refers to summation.
Please refer to Sec3.2 for more details about the attention ratio.

**Comment by 421zuoduan** [comment]
I get it, I have post 2 drafts to explain my view. igonre my terrible handwriting and drawing plz :(

![fig4](https://github.com/lzhxmu/VTW/assets/108874795/ba9ccbd8-e2f5-4602-bf04-2c499848883c)

![fig5](https://github.com/lzhxmu/VTW/assets/108874795/e8afffab-a860-40a9-a079-cd61b714027d)

**Comment by 421zuoduan** [comment]
another question, as you said "information from visual tokens migrates to subsequent text tokens through several layers of attention transformation", Is it possible for image information to be discarded or forgotten during the process of transmission?

**Comment by lzhxmu** [comment]
Nice question! In my opinion, it is indeed possible. This is supported by the fact that the VTW tends to yield slightly worse results than the baseline in certain benchmarks, as presented in Table 2. This discrepancy could be attributed to the loss of information, as you mentioned. However, it is important to note that the transmission process is essentially a black box, making it difficult to subjectively determine whether vision information is discarded or forgotten. Therefore, it is better to conduct additional experiments before drawing  conclusions.
If you think my answer is helpful, please give me a free star.

**Comment by lzhxmu** [comment]
solved
