### ISSUE TITLE
attention mask is not sliced at drop_layer_idx and it might raise error

### ISSUE THREAD

**Issue by EugeneLiu01** [lzhxmu/VTW#2]
Hi! Thanks for your inspiring work!

Im trying to run the cmd
```
python -m llava.serve.cli \
    --model-path liuhaotian/llava-v1.5-7b   \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --use_vtw
```
I typed 'hello' in the terminal, then
The error occures `ValueError: Attention mask should be of size (1, 1, 43, 43), but is torch.Size([1, 1, 619, 619])` at `miniconda3/envs/vtw/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py, line 424`.

It seems to be because the attention mask has not been sliced at [this part](https://github.com/lzhxmu/VTW/blob/34a41991e3135c269adbc0c35bb301cbfcbf3e3e/llava/model/language_model/VTW.py#L293).

**Comment by lzhxmu** [comment]
Thank you for focussing on our paper.
This bug may be caused by different environments.
You can add one line of code to line 424 of file "miniconda3/envs/vtw/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py" like this:
```python
if attention_mask is not None:
    attention_mask = attention_mask[:, :, :q_len, :kv_seq_len] # add this line
    if attention_mask.size() != (bsz, 1, q_len, kv_seq_len):
        raise ValueError(
            f"Attention mask should be of size {(bsz, 1, q_len, kv_seq_len)}, but is {attention_mask.size()}"
        )
    attn_weights = attn_weights + attention_mask

```
If this is helpful, please give me a free star.

**Comment by EugeneLiu01** [comment]
Thanks for your timely reply. It works!

By the way, I configured the environment according to the readme and the versions of most packages is the same as `pyproject.toml` exceept `torch==2.0.1`. Is it because of the version of `transformers`? Mine is `4.37.2`. What is the version of yours?

Starred!

**Comment by lzhxmu** [comment]
This may be due to different torch versions  because my transformers version is 4.37.2 too.

**Comment by EugeneLiu01** [comment]
I will make more attempt. Thanks!

And i have a question about the selection of visual token withdrawal layer. Is it a fixed number after searching and able to general other task or one for each task?

**Comment by lzhxmu** [comment]
It's better to search for each task, but simply setting the visual token withdrawal layer as $N/2$ is okay in most tasks. N is the total layer numbers.
