### ISSUE TITLE
Question about Table 1

### ISSUE THREAD

**Issue by 421zuoduan** [lzhxmu/VTW#3]
Hi, thanks for your great work.

I have a question about Table 1. `In both (b) and (c), we remove vision tokens in the 16-th layer of LLaVA-1.5-7b`, does it ONLY remove the vision tokens in the 16-th layer? or it is just a mistake while writing?

In (b) and (c), I think this study has remove vision tokens in the last 16 layers with llava-1.5-7B. (a) removes all vision tokens across all layers, (b) replaces the origin image with a misleading image full of white area at the first 16 layers and removes vision tokens in the last 16 layers, (c) only remove vision tokens in the last 16 layers. Am I right?

I would appreciate it if u could answer my question.

**Comment by lzhxmu** [comment]
You're right. The caption of Table 1 is confusing. To clarify, it's the last 16 layers, not the 16th layer.

**Comment by 421zuoduan** [comment]
Thanks for your reply, it quite helps me a lot.
