### ISSUE TITLE
reproduce latency results

### ISSUE THREAD

**Issue by cool-xiang** [lzhxmu/VTW#4]
Hello, thank you for your excellent work! I would like to ask how to reproduce the latency in the article and where to test the running time in the code. Thank you very much for your reply!

**Comment by lzhxmu** [comment]
Thank you for your attention to our work, and hope the delayed reply is still helpful to you.

As described in the paper, we tested the latency of VTW on the SQA_img dataset, so you just need to compare the time on this dataset with and without VTW. The total time cost will be displayed on the right side of the progress bar like:
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/341a4ae1-aef8-400d-8f55-aa1b71ad535d">
